# Generated by Django 2.1 on 2018-08-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180826_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='Choice',
        ),
    ]
